import re
import streamlit as st
from dotenv import load_dotenv
import os
import google.generativeai as genai

from datetime import datetime
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from io import BytesIO

# ---------------- PDF Function ---------------- #

def generate_pdf(review_text, submitted_code, language):
    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40
    )

    styles = getSampleStyleSheet()

    # Times New Roman styles
    styles["Title"].fontName = "Times-Bold"
    styles["Heading2"].fontName = "Times-Bold"
    styles["BodyText"].fontName = "Times-Roman"

    styles["Heading2"].textColor = "#003366"

    styles["Title"].fontSize = 18
    styles["Heading2"].fontSize = 14
    styles["BodyText"].fontSize = 11

    # Clean unwanted markdown
    review_text = review_text.replace("#", "")
    review_text = review_text.replace("**", "")
    review_text = review_text.replace("```java", "")
    review_text = review_text.replace("```python", "")
    review_text = review_text.replace("```cpp", "")
    review_text = review_text.replace("```c", "")
    review_text = review_text.replace("```javascript", "")
    review_text = review_text.replace("```", "")

    elements = []

    # Title
    elements.append(
        Paragraph("AI Code Review Report", styles["Title"])
    )

    elements.append(Spacer(1, 15))

    # Metadata
    current_date = datetime.now().strftime("%d %B %Y")

    elements.append(
        Paragraph(
            "<b>Generated By:</b> AI Code Review Assistant",
            styles["BodyText"]
        )
    )

    elements.append(
        Paragraph(
            f"<b>Date:</b> {current_date}",
            styles["BodyText"]
        )
    )

    elements.append(
        Paragraph(
            f"<b>Language:</b> {language}",
            styles["BodyText"]
        )
    )

    elements.append(Spacer(1, 15))

    # Submitted Code
    elements.append(
        Paragraph("Submitted Code", styles["Heading2"])
    )

    formatted_code = (
        submitted_code
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("\n", "<br/>")
    )

    elements.append(
        Paragraph(
            f"<font face='Courier'>{formatted_code}</font>",
            styles["BodyText"]
        )
    )

    elements.append(Spacer(1, 15))

    # Review Summary
    # Review Summary
    elements.append(
        Paragraph("Review Summary", styles["Heading2"])
    )

    elements.append(Spacer(1, 10))

    # Clean markdown symbols
    formatted_review = review_text

    formatted_review = formatted_review.replace("#", "")
    formatted_review = formatted_review.replace("**", "")

            # Add headings properly
    headings = [
                "Bugs Found",
                "Corrected Code",
                "Time Complexity",
                "Space Complexity",
                "Interview Questions",
                "Test Cases"
            ]

    for heading in headings:
                formatted_review = formatted_review.replace(
                    heading,
                    f"<br/><br/><b>{heading}</b><br/>"
                )

            # Put numbered points on separate lines
    formatted_review = formatted_review.replace("1. ", "<br/>1. ")
    formatted_review = formatted_review.replace("2. ", "<br/>2. ")
    formatted_review = formatted_review.replace("3. ", "<br/>3. ")

    # Preserve line breaks
    formatted_review = formatted_review.replace("\n", "<br/>")

    elements.append(
                Paragraph(formatted_review, styles["BodyText"])
            )

            # Build PDF ONLY ONCE
    doc.build(elements)

    buffer.seek(0)

    return buffer.getvalue()


# ---------------- Gemini Setup ---------------- #

load_dotenv()

genai.configure(api_key=os.getenv("GEMINI_API_KEY"))


# ---------------- Streamlit UI ---------------- #

st.set_page_config(
    page_title="AI Code Reviewer",
    page_icon="🤖",
    layout="wide"
)

st.title("🤖 AI-Powered Code Review Assistant")

st.write(
    "Paste your code below, choose the programming language, and click Analyze."
)

language = st.selectbox(
    "Select Programming Language",
    ["Python", "Java", "C++", "C", "JavaScript"]
)

uploaded_file = st.file_uploader(
    "📁 Upload Code File",
    type=["py", "java", "cpp", "c", "js"]
)

# ---------------- Code Input ---------------- #

if uploaded_file is not None:

    code = uploaded_file.read().decode("utf-8")

    st.success(f"✅ {uploaded_file.name} uploaded successfully!")

    st.text_area(
        "Uploaded Code",
        value=code,
        height=300
    )

else:

    code = st.text_area(
        "Paste Your Code Here",
        height=300,
        placeholder="Example:\nfor i in range(5):\n    print(i)"
    )


# ---------------- Analyze ---------------- #

if st.button("Analyze Code"):

    if code.strip() == "":

        st.warning("⚠️ Please paste some code first.")

    else:

        with st.spinner("🤖 Gemini is reviewing your code..."):

            try:

                model = genai.GenerativeModel(
                    "models/gemini-2.5-flash"
                )

                prompt = f"""
You are a Senior Software Engineer.

Review the following {language} code.

Generate a SHORT report suitable for final-year engineering students preparing for placements.

Rules:
- Keep answers concise.
- Do NOT use markdown symbols (#, **).
- Limit Bugs Found to 3 points.
- Mention Severity (High/Medium/Low).
- Provide corrected code only if required.
- Add a Changes Made section.
- Mention only Big-O notation.
Generate exactly 3 placement-oriented interview questions.

IMPORTANT:
- Put each question on a NEW LINE.
- Use this format:

1. Question 1

2. Question 2

3. Question 3


Generate exactly 3 beginner-friendly test cases.

IMPORTANT:
- Put each test case on a NEW LINE.
- Use this format:

1. Test Case

2. Test Case

3. Test Case

- Provide Code Quality Scores.

Sections:

Code Quality Scores
Readability: X/10
Efficiency: X/10
Maintainability: X/10

Bugs Found

Changes Made

Corrected Code

Time Complexity

Space Complexity

Interview Questions

Test Cases

Code:
{code}
"""

                response = model.generate_content(prompt)

                readability = re.search(
                    r"Readability:\s*(\d+/10)",
                    response.text
                )

                efficiency = re.search(
                    r"Efficiency:\s*(\d+/10)",
                    response.text
                )

                maintainability = re.search(
                    r"Maintainability:\s*(\d+/10)",
                    response.text
                )

                st.success("✅ Analysis Complete!")

                col1, col2, col3 = st.columns(3)

                col1.metric(
                        "Readability",
                        readability.group(1) if readability else "N/A"
                    )

                col2.metric(
                        "Efficiency",
                        efficiency.group(1) if efficiency else "N/A"
                    )

                col3.metric(
                        "Maintainability",
                        maintainability.group(1) if maintainability else "N/A"
                    )

                st.divider()

                formatted_response = response.text

                    # Put numbered points on separate lines
                formatted_response = re.sub(r'\s+(\d+\.)', r'\n\n\1', formatted_response)

                    # Remove extra blank lines
                formatted_response = re.sub(r'\n{3,}', '\n\n', formatted_response)

                formatted_response = formatted_response.replace(
                    "Bugs Found",
                    "<h3 style='color:white; font-weight:bold;'>Bugs Found</h3>"
                )

                formatted_response = formatted_response.replace(
                    "Corrected Code",
                    "<h3 style='color:white; font-weight:bold;'>Corrected Code</h3>"
                )

                formatted_response = formatted_response.replace(
                    "Time Complexity",
                    "<h3 style='color:white; font-weight:bold;'>Time Complexity</h3>"
                )

                formatted_response = formatted_response.replace(
                    "Space Complexity",
                    "<h3 style='color:white; font-weight:bold;'>Space Complexity</h3>"
                )

                formatted_response = formatted_response.replace(
                    "Interview Questions",
                    "<h3 style='color:white; font-weight:bold;'>Interview Questions</h3>"
                )

                formatted_response = formatted_response.replace(
                    "Test Cases",
                    "<h3 style='color:white; font-weight:bold;'>Test Cases</h3>"
                )

                st.markdown(formatted_response, unsafe_allow_html=True)

                pdf_data = generate_pdf(
                    response.text,
                    code,
                    language
                )

                st.download_button(
                    label="📄 Download Review Report",
                    data=pdf_data,
                    file_name="AI_Code_Review_Report.pdf",
                    mime="application/pdf"
                )

            except Exception as e:

                st.error(f"Error: {e}")